baseURL: "https://sifi.no/"
languageCode: "en-us"
title: "SIFI"
theme: "PaperMod"


params:
  defaultTheme: light 
  homeInfoParams:
    Title: "SIFI - Sikkerhet på IFI"
    Content: "SIFI er en linjeforening til masterprogrammet Informasjonssikkerhet på UiO. \n\n "
  socialIcons:
    - name: facebook
      url: "https://www.facebook.com/profile.php?id=100091625065665"
    - name: discord
      url: "https://discord.com/invite/rgE66SkUAt"
    - name: instagram
      url: "https://www.instagram.com/sikkerhetifi/"


  ShowBreadCrumbs: True
  ShowPostNavLinks: true


menu:
  main:
    - identifers: home
      name: Hjem
      url: /
      weight: 10
    - identifers: omoss
      name: Om oss
      url: /omoss
      weight: 20
    - identifier: ctf
      name: CTF
      url: /ctf/
      weight: 30
    - identifier: Bedrift
      name: Bedrift
      url: /bedrift/
      weight: 40
    - identifier: archives
      name: Arkiv
      url: /archives/
      weight: 50
